aliyun/aliyun-cli

- README.rst
Still some missing content (and probably remaining formatting and English grammar errors), but at least it's readable.
> Fix #19 - README.RST formatting errors

- aliyuncli/aliyunOpenApiData.py
patch[issues/14](https://github.com/aliyun/aliyun-cli/issues/14)
> patch to use in ubuntu

- README.md
- README_cn.md
* English first
* add HTTPS section
* some cleanup
> Document update

- README.md
- README_zh.md
> 增加api explorer 链接地址

- cli/flag.go
- config/config_suite_test.go
- config/configure_get.go
- config/profile.go
- openapi/output_filter.go
- openapi/pager_test.go
- openapi/restful.go
- oss/lib/config.go
- oss/lib/cp.go
- oss/lib/option.go
- oss/lib/symlink_test.go
modify some files to pass command `go vet`:
```
go vet ./cli/... ./command/... ./config/... ./i18n/... ./main/... ./openapi/... ./oss/... ./resource/...
```
> pass command `go vet`

- cli/context.go
- cli/flag.go
- cli/flag_field.go
- cli/flag_set.go
- cli/flag_test.go
- cli/parser.go
- cli/parser_test.go
- config/flags_test.go
if block problem:
```
if block ends with a return statement, so drop this else and outdent its block
```
prefected testcases of some file:
cli/flag.go 
config/flags.go
> prefected if block problem and testcases

- cli/color_test.go
- cli/command_help_test.go
- cli/command_test.go
- cli/exit_code_test.go
Prefected  of package cli：
cli/color.go
cli/command_help.go
cli/exit_code.go
cli/command.go
> Prefected testcases of package cli

- config/configuration_test.go
- config/hello_test.go
- config/profile_test.go
- config/user_agent_test.go
Perfected testcases for package config:
config/configuration.go
config/hello.go
config/profile.go
config/user_agent.go
> Perfected testcases for package config

- config/configuration.go
- config/configuration_test.go
- config/configure.go
- config/configure_delete.go
- config/configure_delete_test.go
- config/configure_get.go
- config/configure_get_test.go
- config/configure_list.go
- config/configure_list_test.go
- config/configure_set.go
- config/configure_set_test.go
- config/configure_test.go
- config/legacy_test.go
add mock function for :
```func LoadConfiguration(w io.Writer) (Configuration, error)```
```func SaveConfiguration(config Configuration) error```
> perfected testcases of package config and add mock function

- config/configuration_test.go
- config/configure_delete_test.go
- config/configure_get_test.go
- config/configure_list_test.go
- config/configure_set_test.go
- config/configure_test.go
Improve test coverage of cli and config to 85%
> Improve test coverage of package cli and config

- CHANGELOG.md
- openapi/commando_test.go
- openapi/output_filter.go
- openapi/output_filter_test.go
> update flag `--output`

- CHANGELOG.md
- openapi/output_filter.go
- openapi/output_filter_test.go
- openapi/pager.go
- openapi/pager_test.go
> Improve user experience

- CHANGELOG.md
- Makefile
- README-CN.md
- README.md
- appveyor.yml
- update: meta data
- fix: help generating information bug
- Upgrade the ossutil component to version 1.6.6
- Package manager switches to Go Modules
> Release v3.0.26

- openapi/commando.go
- openapi/commando_test.go
fix json.Unmarshal missing precision
> fix json.Unmarshal missing precision

- cli/completion_installer_test.go
- cli/completion_utils_test.go
Signed-off-by: Xuanwo <github@xuanwo.io>
Related to https://github.com/aliyun/aliyun-cli/issues/568
> fix: Skip dangerous tests while not in CI

- README.md
Copied and translate from chinese version.
> Documented --output and --waiter in README.md

- .github/workflows/go.yml
- .github/workflows/installer.yml
- openapi/output_filter.go
- openapi/output_filter_test.go
Allow array results to be displayed in table mode
> Allow array results to be displayed in table mode

- config/profile.go
Fix the nested ChainableRamRoleArn error
> Fix the nested ChainableRamRoleArn error

- cli/context.go
- main/main.go
- main/main_test.go
- oss/lib/cli_bridge.go
Add insecure flag support and update endpoint handling
> Add insecure flag support and update endpoint handling

- openapi/rpc.go
Implement retry logic for throttling errors in RPC calls
> Implement retry logic for throttling errors in RPC calls

- README.md
- cli/version.go
- cloudsso/access_configurations.go
- cloudsso/access_configurations_test.go
- cloudsso/login.go
- cloudsso/login_test.go
- cloudsso/refresh.go
- cloudsso/refresh_test.go
- cloudsso/user.go
- cloudsso/user_test.go
- config/configuration.go
- config/configure.go
- config/configure_delete.go
- config/configure_get.go
- config/configure_get_test.go
- config/configure_list.go
- config/configure_list_test.go
- config/configure_set.go
- config/configure_set_test.go
- config/configure_test.go
- config/flags.go
- config/profile.go
- config/profile_test.go
- i18n/environment.go
- i18n/text.go
- i18n/text_test.go
- util/util.go
- util/util_test.go
Add CloudSSO authentication support and related configurations
> Add CloudSSO authentication support and related configurations

- meta/repository.go
- meta/repository_test.go
Fix: Scenario where API allows multiple methods to access
> Fix: Scenario where API allows multiple methods to access

- README.md
- config/configure.go
- config/configure_get.go
- config/configure_list.go
- config/configure_oauth_test.go
- config/configure_set.go
- config/configure_test.go
- config/flags.go
- config/flags_test.go
- config/profile.go
- config/profile_test.go
- config/start_oauth_flow_test.go
- go.mod
- go.sum
- util/util.go
- util/util_test.go
> Support oauth profile type
